name: Health Check

on: 
  schedule:
    - cron: 45,46,47,48,49,50  * * * *

jobs: 
  test_schedule: 
    runs-on: ubuntu-20.04
    steps:
      - name: Check deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: http://fullstackopen-cicd-fazzolari17.herokuapp.com
          retry-attemps: 5
          retry-delay: 30s

