name: Health Check

on: 
  schedule:
  # will check once a day at 5:30 am 
    - cron: 30, 5 * * *

jobs: 
  test_schedule: 
    runs-on: ubuntu-20.04
    steps:
      - name: Check deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: http://fullstackopen-cicd-fazzolari17.herokuapp.com
          max-attempts: 5
          retry-delay: 30s

